# Generated by Django 4.2.4 on 2023-08-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materias_Por_Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Materias_Por_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos_Por_Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.materia')),
            ],
        ),
    ]
