# Generated by Django 4.2.4 on 2023-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dia',
            field=models.CharField(max_length=10),
        ),
    ]
