# Generated by Django 4.2.4 on 2023-08-15 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='horario',
        ),
        migrations.AddField(
            model_name='materia',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='materia',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio'),
        ),
    ]
