# Generated by Django 4.2.4 on 2023-08-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_clase_dia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('materia', 'hora', 'dia')},
        ),
    ]
