# Generated by Django 4.2.4 on 2023-08-15 19:34

from django.db import migrations, models
import django.db.models.deletion
import horarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_remove_materia_horario_materia_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos_por_maestro',
            name='materia',
        ),
        migrations.AddField(
            model_name='alumnos_por_maestro',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.alumno'),
        ),
    ]
