# Generated by Django 4.2.4 on 2023-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_alter_alumnos_por_maestro_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias_por_alumno',
            name='materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='horarios.materia'),
        ),
    ]
