# Generated by Django 4.2.4 on 2023-09-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_docente_grupo_materia_clase_grupohasestudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.docente'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.materia'),
        ),
    ]
